name: schedule

on: [pull_request, push, workflow_dispatch]

jobs:
  schedule:
    runs-on: ubuntu-latest
    env:
      path: homework/schedule/build
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Create build directory
      run: mkdir ${{ env.path }}
    - name: Compile
      working-directory: ${{ env.path }}
      run: |
        cmake ..
        make
    - name: Run tests
      working-directory: ${{ env.path }}
      run: ctest -V
